name: Update Wiki
on:
  workflow_dispatch:
    inputs:
      CONTENT:
        description: 'Supra environments to generate manifest files'
        required: false
        default: ''
jobs:
  update-wiki:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Update Wiki
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: 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
          external_repository: itzargomez/githubpages_test.wiki
          publish_dir: .wiki
